"use client";

import { useState } from "react";
import { CheckCircle2, Loader2, Mail, Phone } from "lucide-react";
import { getSupabase } from "@/lib/supabase";

const initial = { name: "", email: "", phone: "", destination: "", travelers: "2", dates: "", budget: "", message: "" };
export default function ContactPage() {
  const [form, setForm] = useState(initial);
  const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error">("idle");
  const update = (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setStatus("sending"); try { const { error } = await getSupabase().from("inquiries").insert([{ name: form.name, email: form.email, phone: form.phone, destination: form.destination, travelers: Number(form.travelers), travel_dates: form.dates, budget: form.budget, message: form.message }]); if (error) throw error; setStatus("sent"); setForm(initial); } catch { const subject = encodeURIComponent(`Private inquiry from ${form.name || "website visitor"}`); const body = encodeURIComponent(`Name: ${form.name}\nEmail: ${form.email}\nPhone: ${form.phone}\nConsidering: ${form.destination}\nDates: ${form.dates}\nTravelers: ${form.travelers}\n\n${form.message}`); window.location.href = `mailto:sales@awgotravel.com?subject=${subject}&body=${body}`; setStatus("error"); } };
  return <><section className="bg-navy px-5 pb-16 pt-36 text-white sm:px-8 lg:pb-24"><div className="mx-auto max-w-7xl"><p className="text-[10px] font-semibold uppercase tracking-[.3em] text-gold">Private inquiry</p><h1 className="font-editorial mt-6 max-w-3xl text-5xl leading-[.98] sm:text-7xl">Begin with a private conversation.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/65">Tell us the shape of the journey you have in mind. We will respond to arrange a confidential consultation.</p></div></section><section className="bg-stone px-5 py-16 sm:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.8fr_1.2fr]"><aside><p className="text-[10px] font-semibold uppercase tracking-[.25em] text-gold">Direct contact</p><a href="mailto:sales@awgotravel.com" className="mt-6 flex items-center gap-3 text-lg text-navy hover:text-gold"><Mail size={18}/>sales@awgotravel.com</a><a href="tel:+14099953371" className="mt-4 flex items-center gap-3 text-lg text-navy hover:text-gold"><Phone size={18}/>+1 409 995-3371</a><p className="mt-10 max-w-sm leading-7 text-navy/65">AW GOTRAVEL provides private travel design and lifestyle coordination. We do not sell flights, rooms, tickets, tours or packages.</p></aside><form onSubmit={submit} className="grid gap-5 border-t border-navy/20 pt-6"><div className="grid gap-5 sm:grid-cols-2"><Field label="Name" name="name" value={form.name} update={update} required/><Field label="Email" name="email" type="email" value={form.email} update={update} required/></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Phone" name="phone" value={form.phone} update={update}/><Field label="Where are you considering?" name="destination" value={form.destination} update={update}/></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Approximate dates" name="dates" value={form.dates} update={update}/><Field label="Number of travelers" name="travelers" type="number" value={form.travelers} update={update}/></div><label className="grid gap-2 text-[10px] font-semibold uppercase tracking-[.16em] text-navy">Tell us what matters<textarea name="message" value={form.message} onChange={update} required rows={6} className="mt-1 border border-navy/25 bg-white p-4 text-base font-normal normal-case tracking-normal text-navy outline-none focus:border-gold" /></label>{status === "sent" && <p className="flex gap-2 text-sm text-navy"><CheckCircle2 className="text-gold" size={18}/>Thank you. Your private inquiry has been received.</p>}{status === "error" && <p className="text-sm text-red-700">We could not send this inquiry. Please email us directly.</p>}<button disabled={status === "sending"} className="inline-flex w-fit items-center gap-3 bg-navy px-6 py-4 text-[11px] font-bold uppercase tracking-[.15em] text-white hover:bg-gold hover:text-navy disabled:opacity-60">{status === "sending" && <Loader2 size={15} className="animate-spin"/>}Request a consultation</button></form></div></section></>;
}
function Field({label,name,value,update,type="text",required=false}:{label:string;name:string;value:string;update:(event:React.ChangeEvent<HTMLInputElement>)=>void;type?:string;required?:boolean}){return <label className="grid gap-2 text-[10px] font-semibold uppercase tracking-[.16em] text-navy">{label}<input type={type} name={name} value={value} onChange={update} required={required} className="border border-navy/25 bg-white px-4 py-3 text-base font-normal normal-case tracking-normal text-navy outline-none focus:border-gold"/></label>}